import type { Metadata, Viewport } from "next";
import "@/app/styles/globals.css";
import { Providers } from "@/app/providers";
import { motion } from "framer-motion";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // Désactive le zoom
};

// Configuration de metadata
export const metadata: Metadata = {
  title: "Fahim Gharsa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
